CREATE OR REPLACE FUNCTION extract_references(refs JSONB) RETURNS BIGINT [] LANGUAGE SQL IMMUTABLE AS $$
  SELECT COALESCE(array_agg(i::bigint), '{}') FROM (SELECT jsonb_array_elements(jsonb_path_query_array(refs, '$.*[*]')) i) exrefs;
$$;

ALTER TABLE PUBLIC."Concept" RENAME COLUMN CONTENT TO LITERAL_CONTENT;
DROP INDEX "Concept_content";
CREATE INDEX CONCEPT_LITERAL_CONTENT_IDX ON PUBLIC."Concept" USING GIN (
    LITERAL_CONTENT JSONB_OPS
);

ALTER TABLE PUBLIC."Concept" ADD COLUMN REFERENCE_CONTENT JSONB NOT NULL DEFAULT '{}'::JSONB;

ALTER TABLE PUBLIC."Concept" ADD COLUMN REFS BIGINT [] NOT NULL GENERATED ALWAYS AS (extract_references(REFERENCE_CONTENT)) STORED;

CREATE INDEX CONCEPT_REFS_IDX ON PUBLIC."Concept" USING GIN (REFS);

