import { execSync } from "node:child_process";
import { writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(__filename);
const projectRoot = join(__dirname, "..");

if (process.env.HOME !== "/vercel") {
  try {
    execSync("supabase start", { cwd: projectRoot, stdio: "inherit" });
    execSync("supabase migrations up", { cwd: projectRoot, stdio: "inherit" });
    const stdout = execSync(
      "supabase gen types typescript --local --schema public",
      { encoding: "utf8", cwd: projectRoot },
    );
    writeFileSync(
      join(projectRoot, "src", "dbTypes.ts"),
      "// Generated by supabase -- do not edit\n" + stdout,
    );
  } catch (err) {
    console.error(err);
    throw err;
  }
}
