packages:
  - packages/*
  - apps/*

catalog:
  react: ^19.1.0
  react-dom: ^19.1.0
  "@types/react": ^19.1.0
  "@types/react-dom": ^19.1.0

catalogs:
  obsidian:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ^19.0.0
    "@types/react-dom": ^19.0.0
  roam:
    react: 18.2.0
    react-dom: 18.2.0
    "@types/react": 18.2.0
    "@types/react-dom": 18.2.0
  blueprint:
    react: 17.0.2
    react-dom: 17.0.2
    "@types/react": 17.0.2
    "@types/react-dom": 17.0.2

onlyBuiltDependencies:
  - core-js
  - core-js-pure
  - esbuild
  - react-vertical-timeline-component
  - roamjs-components
  - sharp
  - supabase
  - unrs-resolver

packageExtensions:
  "@blueprintjs/core":
    dependencies:
      react: 17.0.2
      react-dom: 17.0.2
      "@types/react": 17.0.2
      "@types/react-dom": 17.0.2
  "@blueprintjs/datetime":
    dependencies:
      react: 17.0.2
      react-dom: 17.0.2
      "@types/react": 17.0.2
      "@types/react-dom": 17.0.2
  "@blueprintjs/select":
    dependencies:
      react: 17.0.2
      react-dom: 17.0.2
      "@types/react": 17.0.2
      "@types/react-dom": 17.0.2
  "@types/react-dom@18.2.0":
    dependencies:
      "@types/react": 18.2.0
  "@types/react-dom@17.0.2":
    dependencies:
      "@types/react": 17.0.2

peerDependencyRules:
  allowedVersions:
    "roamjs-components>tslib": ^2

patchedDependencies:
  tldraw@^2.3.0: patches/tldraw@2.3.0.patch
  "@tldraw/editor@^2.3.0": patches/@tldraw__editor@2.3.0.patch

allowUnusedPatches: false
