packages:
  - packages/*
  - apps/*

allowUnusedPatches: false

allowedDeprecatedVersions:
  "@humanwhocodes/config-array": ^0.13
  "@humanwhocodes/object-schema": ^2.0
  "@playwright/test": ^1.29
  "@types/minimatch": ^6.0
  abab: ^2.0
  domexception: 4.0.0
  eslint: ^8.57
  glob: ^7.2
  inflight: ^1.0
  lodash.get: ^4.4
  lodash.isequal: ^4.5
  node-domexception: ^1.0
  path-match: ^1.2
  popper.js: ^1.16
  rimraf: <4

# The global versions. In the react case, applies to website in practice
catalog:
  "@types/eslint": 8.56.12
  "@types/react": ^19.1.12
  "@types/react-dom": ^19.1.9
  eslint: 8.57.1
  react: ^19.1.0
  react-dom: ^19.1.0
  "@supabase/supabase-js": 2.76.1
  "@supabase/functions-js": 2.76.1
  "@supabase/auth-js": 2.76.1

catalogs:
  obsidian:
    "@types/react": ^19.0.12
    "@types/react-dom": ^19.0.4
    react: 19.0.0
    react-dom: 19.0.0
  roam:
    "@types/react": 18.2.21
    "@types/react-dom": 18.2.17
    react: 18.2.0
    react-dom: 18.2.0

onlyBuiltDependencies:
  - core-js
  - core-js-pure
  - esbuild
  - react-vertical-timeline-component
  - roamjs-components
  - sharp
  - supabase
  - unrs-resolver

overrides:
  "@types/react-dom@18.2.17>@types/react": 18.2.21
  "@types/react-vertical-timeline-component@3.3.6>@types/react": 18.2.21
  react-charts@3.0.0-beta.57>@types/react: 18.2.21
  react-charts@3.0.0-beta.57>@types/react-dom: 18.2.17
  roam>@types/react: 18.2.21
  roam>@types/react-dom: 18.2.17
  roam>react: 18.2.0
  roam>react-dom: 18.2.0

patchedDependencies:
  "@blueprintjs/core@^3.50.4": patches/@blueprintjs__core@3.50.4.patch
  "@blueprintjs/select@3.19.1": patches/@blueprintjs__select@3.19.1.patch
  "@tldraw/editor@^2.3.0": patches/@tldraw__editor@2.3.0.patch
  tldraw@2.3.0: patches/tldraw@2.3.0.patch

peerDependencyRules:
  allowedVersions:
    "@blueprintjs/core>react": 18.2.0
    "@blueprintjs/core>react-dom": 18.2.0
    "@blueprintjs/datetime>react": 18.2.0
    "@blueprintjs/datetime>react-dom": 18.2.0
    "@blueprintjs/select>react": 18.2.0
    "@blueprintjs/select>react-dom": 18.2.0
    "@next/eslint-plugin-next": ^15.0
    "@samepage/scripts>tailwindcss": 3.4.17
    react-day-picker@7.4.9>react: 18.2.0
    react-in-viewport>react: 18.2.0
    react-in-viewport>react-dom: 18.2.0
    react-popper@1.3.11>react: 18.2.0
    roamjs-components>@blueprintjs/select: 3.19.1
    roamjs-components>@types/react: 18.2.21
    roamjs-components>@types/react-dom: 18.2.17
    roamjs-components>idb: ^7.1
    roamjs-components>react: 18.2.0
    roamjs-components>react-dom: 18.2.0
    roamjs-components>tslib: ^2
