packages:
  - packages/*
  - apps/*

catalog:
  react: ^19.1.0
  react-dom: ^19.1.0
  "@types/react": ^19.1.0
  "@types/react-dom": ^19.1.0

catalogs:
  obsidian:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ^19.0.0
    "@types/react-dom": ^19.0.0
  roam:
    react: 18.2.0
    react-dom: 18.2.0
    "@types/react": 18.2.21
    "@types/react-dom": 18.2.17
    # "@types/react": 17.0.39
    # "@types/react-dom": 17.0.13

onlyBuiltDependencies:
  - core-js
  - core-js-pure
  - esbuild
  - react-vertical-timeline-component
  - roamjs-components
  - sharp
  - supabase
  - unrs-resolver

overrides:
  "roam>react": 18.2.0
  "roam>react-dom": 18.2.0
  "roam>@types/react": 18.2.21
  "roam>@types/react-dom": 18.2.17
  "@types/react-vertical-timeline-component@3.3.6>@types/react": "18.2.21"
  "@types/react-dom@18.2.17>@types/react": "18.2.21"
  "react-charts@3.0.0-beta.57>@types/react": "18.2.21"
  "react-charts@3.0.0-beta.57>@types/react-dom": "18.2.17"

peerDependencyRules:
  allowedVersions:
    "roamjs-components>tslib": ^2

patchedDependencies:
  tldraw@^2.3.0: patches/tldraw@2.3.0.patch
  "@tldraw/editor@^2.3.0": patches/@tldraw__editor@2.3.0.patch

allowUnusedPatches: false
