/**
 * Register command palette commands for Query Builder testing
 * Generated by opencode with Sonnet 4.5
 */

import type { OnloadArgs } from "roamjs-components/types/native";
import getPageTitleByPageUid from "roamjs-components/queries/getPageTitleByPageUid";
import {
  runAllTests,
  runSingleTest,
  formatTestResults,
  formatBenchmarkResults,
} from "./testQueryBuilder";
import getPageTitlesStartingWithPrefix from "roamjs-components/queries/getPageTitlesStartingWithPrefix";

const registerQueryBuilderTestCommands = async ({
  extensionAPI,
}: OnloadArgs): Promise<void> => {
  // Command: Run all Query Builder tests
  await extensionAPI.ui.commandPalette.addCommand({
    label: "Query Builder: Run All Tests",
    callback: () => {
      console.group("🧪 Query Builder Test Suite");
      console.log("Running all tests...");

      runAllTests()
        .then((results) => {
          console.log(formatTestResults(results));
          console.log(formatBenchmarkResults(results));

          const passedCount = results.filter((r) => r.passed).length;
          const totalCount = results.length;

          if (passedCount === totalCount) {
            console.log(
              `%c✓ All tests passed! (${passedCount}/${totalCount})`,
              "color: green; font-weight: bold; font-size: 14px;",
            );
          } else {
            console.log(
              `%c✗ Some tests failed: ${passedCount}/${totalCount} passed`,
              "color: red; font-weight: bold; font-size: 14px;",
            );
          }

          console.groupEnd();
        })
        .catch((error) => {
          console.log(error);
        });
    },
  });

  // Command: Run current page as test
  await extensionAPI.ui.commandPalette.addCommand({
    label: "Query Builder: Run Test on Current Page",
    callback: () => {
      window.roamAlphaAPI.ui.mainWindow
        .getOpenPageOrBlockUid()
        .then((pageUid) => {
          if (!pageUid) {
            console.error("No page is currently open");
            return;
          }

          const pageTitle = getPageTitleByPageUid(pageUid as unknown as string);

          if (
            !pageTitle ||
            !pageTitle.startsWith("discourse-graph/tests/queries/")
          ) {
            console.error(
              "Current page is not a test page. Test pages must start with 'discourse-graph/tests/queries/'",
            );
            return;
          }

          console.group(`🧪 Running test: ${pageTitle}`);

          runSingleTest(pageTitle)
            .then((result) => {
              if (result.passed) {
                console.log(
                  `%c✓ Test passed in ${result.duration.toFixed(2)}ms`,
                  "color: green; font-weight: bold;",
                );
              } else {
                console.log(
                  `%c✗ Test failed`,
                  "color: red; font-weight: bold;",
                );
                if (result.error) {
                  console.error("Error:", result.error);
                }
                if (result.details) {
                  console.log("Details:", result.details);
                }
              }

              console.groupEnd();
            })
            .catch((error) => {
              console.log(error);
            });
        })
        .catch((error) => {
          console.log(error);
        });
    },
  });

  // Command: Benchmark all tests
  await extensionAPI.ui.commandPalette.addCommand({
    label: "Query Builder: Benchmark Tests",
    callback: () => {
      console.group("⏱️ Query Builder Benchmark");
      console.log("Running benchmark...");

      runAllTests()
        .then((results) => {
          console.log(formatBenchmarkResults(results));
          console.groupEnd();
        })
        .catch((error) => {
          console.log(error);
        });
    },
  });

  // Command: List all test pages
  await extensionAPI.ui.commandPalette.addCommand({
    label: "Query Builder: List All Tests",
    callback: () => {
      const testPages = getPageTitlesStartingWithPrefix(
        "discourse-graph/tests/queries/",
      );

      if (testPages.length === 0) {
        console.log("No test pages found.");
        console.log(
          "Create test pages with titles starting with 'discourse-graph/tests/queries/'",
        );
        return;
      }

      console.group(`📋 Query Builder Tests (${testPages.length})`);
      testPages.forEach((page, index) => {
        console.log(`${index + 1}. ${page}`);
      });
      console.groupEnd();
    },
  });
};

export default registerQueryBuilderTestCommands;
