/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export enum Agentidentifiertype {
  Email = "email",
  Orcid = "orcid",
}

export enum Agenttype {
  Anonymous = "anonymous",
  AutomatedAgent = "automated_agent",
  Organization = "organization",
  Person = "person",
}

export enum Contentvariant {
  Direct = "direct",
  DirectAndChildren = "direct_and_children",
  DirectAndDescription = "direct_and_description",
}

export enum Embeddingname {
  OpenaiTextEmbedding3Large1024 = "openai_text_embedding_3_large_1024",
  OpenaiTextEmbedding3Large256 = "openai_text_embedding_3_large_256",
  OpenaiTextEmbedding3Large3072 = "openai_text_embedding_3_large_3072",
  OpenaiTextEmbedding3Small1536 = "openai_text_embedding_3_small_1536",
  OpenaiTextEmbedding3Small512 = "openai_text_embedding_3_small_512",
  OpenaiTextEmbeddingAda21536 = "openai_text_embedding_ada2_1536",
}

export enum Entitytype {
  AutomatedAgent = "AutomatedAgent",
  Concept = "Concept",
  ConceptSchema = "ConceptSchema",
  Content = "Content",
  ContentLink = "ContentLink",
  Document = "Document",
  Occurrence = "Occurrence",
  Person = "Person",
  Platform = "Platform",
  PlatformAccount = "PlatformAccount",
  Space = "Space",
}

export enum Epistemicstatus {
  Certain = "certain",
  CertainlyNot = "certainly_not",
  Contentious = "contentious",
  CouldBeFalse = "could_be_false",
  CouldBeTrue = "could_be_true",
  StrongEvidenceAgainst = "strong_evidence_against",
  StrongEvidenceFor = "strong_evidence_for",
  Uncertain = "uncertain",
  Unknown = "unknown",
}

export enum Platform {
  Obsidian = "Obsidian",
  Roam = "Roam",
}

export enum Scale {
  Block = "block",
  ChunkUnit = "chunk_unit",
  Document = "document",
  Field = "field",
  Paragraph = "paragraph",
  Phrase = "phrase",
  Post = "post",
  Quote = "quote",
  Section = "section",
  Sentence = "sentence",
}

export enum TaskStatus {
  Active = "active",
  Complete = "complete",
  Failed = "failed",
  Timeout = "timeout",
}

export type ArrayType<T> = ArrayTypeImpl<T> extends (infer U)[]
  ? U[]
  : ArrayTypeImpl<T>;

export type ArrayTypeImpl<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S[], I[], U[]>
  : T[];

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AccessToken {
  accessToken: string;
  code: string | null;
  createdDate: Generated<Timestamp>;
  platformAccountId: Int8 | null;
  requestId: string;
}

export interface AgentIdentifier {
  accountId: Int8;
  identifierType: Agentidentifiertype;
  trusted: Generated<boolean>;
  value: string;
}

export interface Concept {
  arity: Generated<number | null>;
  /**
   * The author of content
   */
  authorId: Int8 | null;
  /**
   * The time when the content was created in the remote source
   */
  created: Timestamp;
  description: string | null;
  epistemicStatus: Generated<Epistemicstatus>;
  id: Generated<Int8>;
  isSchema: Generated<boolean>;
  /**
   * The last time the content was modified in the remote source
   */
  lastModified: Timestamp;
  literalContent: Generated<Json>;
  name: string;
  referenceContent: Generated<Json>;
  refs: Generated<ArrayType<Int8>>;
  representedById: Int8 | null;
  schemaId: Int8 | null;
  /**
   * The space in which the content is located
   */
  spaceId: Int8;
}

export interface ConceptContributors {
  conceptId: Int8;
  contributorId: Int8;
}

export interface Content {
  /**
   * The author of content
   */
  authorId: Int8 | null;
  /**
   * The time when the content was created in the remote source
   */
  created: Timestamp;
  /**
   * The creator of a logical structure, such as a content subdivision
   */
  creatorId: Int8 | null;
  documentId: Int8;
  id: Generated<Int8>;
  /**
   * The last time the content was modified in the remote source
   */
  lastModified: Timestamp;
  metadata: Generated<Json>;
  /**
   * This content is part of a larger content unit
   */
  partOfId: Int8 | null;
  scale: Scale;
  /**
   * The unique identifier of the content in the remote source
   */
  sourceLocalId: string | null;
  /**
   * The space in which the content is located
   */
  spaceId: Int8 | null;
  text: string;
  variant: Generated<Contentvariant>;
}

export interface ContentContributors {
  contentId: Int8;
  contributorId: Int8;
}

export interface ContentEmbeddingOpenaiTextEmbedding3Small1536 {
  model: Generated<Embeddingname>;
  obsolete: Generated<boolean | null>;
  targetId: Int8;
  vector: string;
}

export interface Document {
  /**
   * The author of content
   */
  authorId: Int8;
  /**
   * A large object OID for the downloaded raw content
   */
  contents: number | null;
  /**
   * The time when the content was created in the remote source
   */
  created: Timestamp;
  id: Generated<Int8>;
  /**
   * The last time the content was modified in the remote source
   */
  lastModified: Timestamp;
  metadata: Generated<Json>;
  /**
   * The unique identifier of the content in the remote source
   */
  sourceLocalId: string | null;
  /**
   * The space in which the content is located
   */
  spaceId: Int8 | null;
  url: string | null;
}

export interface MyAccounts {
  accountLocalId: string | null;
  active: boolean | null;
  agentType: Agenttype | null;
  dgAccount: string | null;
  id: Int8 | null;
  metadata: Json | null;
  name: string | null;
  platform: Platform | null;
  writePermission: boolean | null;
}

export interface MyConcepts {
  arity: number | null;
  authorId: Int8 | null;
  created: Timestamp | null;
  description: string | null;
  epistemicStatus: Epistemicstatus | null;
  id: Int8 | null;
  isSchema: boolean | null;
  lastModified: Timestamp | null;
  literalContent: Json | null;
  name: string | null;
  referenceContent: Json | null;
  refs: ArrayType<Int8> | null;
  representedById: Int8 | null;
  schemaId: Int8 | null;
  spaceId: Int8 | null;
}

export interface MyContents {
  authorId: Int8 | null;
  created: Timestamp | null;
  creatorId: Int8 | null;
  documentId: Int8 | null;
  id: Int8 | null;
  lastModified: Timestamp | null;
  metadata: Json | null;
  partOfId: Int8 | null;
  scale: Scale | null;
  sourceLocalId: string | null;
  spaceId: Int8 | null;
  text: string | null;
  variant: Contentvariant | null;
}

export interface MyContentsWithEmbeddingOpenaiTextEmbedding3Small1536 {
  authorId: Int8 | null;
  created: Timestamp | null;
  creatorId: Int8 | null;
  documentId: Int8 | null;
  id: Int8 | null;
  lastModified: Timestamp | null;
  metadata: Json | null;
  model: Embeddingname | null;
  partOfId: Int8 | null;
  scale: Scale | null;
  sourceLocalId: string | null;
  spaceId: Int8 | null;
  text: string | null;
  variant: Contentvariant | null;
  vector: string | null;
}

export interface MyDocuments {
  authorId: Int8 | null;
  contents: number | null;
  created: Timestamp | null;
  id: Int8 | null;
  lastModified: Timestamp | null;
  metadata: Json | null;
  sourceLocalId: string | null;
  spaceId: Int8 | null;
  url: string | null;
}

export interface MySpaces {
  id: Int8 | null;
  name: string | null;
  platform: Platform | null;
  url: string | null;
}

export interface PlatformAccount {
  accountLocalId: string;
  active: Generated<boolean>;
  agentType: Generated<Agenttype>;
  dgAccount: string | null;
  id: Generated<Int8>;
  metadata: Generated<Json>;
  name: string;
  platform: Platform;
  writePermission: Generated<boolean>;
}

export interface Result {
  max: Timestamp | null;
}

export interface Space {
  id: Generated<Int8>;
  name: string;
  platform: Platform;
  url: string;
}

export interface SpaceAccess {
  /**
   * The identity of the account in this space
   */
  accountId: Int8;
  editor: boolean;
  /**
   * The space in which the content is located
   */
  spaceId: Int8;
}

export interface SyncInfo {
  failureCount: Generated<number | null>;
  id: Generated<number>;
  lastTaskEnd: Timestamp | null;
  lastTaskStart: Timestamp | null;
  status: Generated<TaskStatus | null>;
  syncFunction: string | null;
  syncTarget: Int8 | null;
  targetType: Generated<Entitytype>;
  taskTimesOutAt: Timestamp | null;
  worker: string;
}

export interface DB {
  accessToken: AccessToken;
  AgentIdentifier: AgentIdentifier;
  Concept: Concept;
  conceptContributors: ConceptContributors;
  Content: Content;
  contentContributors: ContentContributors;
  ContentEmbeddingOpenaiTextEmbedding3Small1536: ContentEmbeddingOpenaiTextEmbedding3Small1536;
  Document: Document;
  myAccounts: MyAccounts;
  myConcepts: MyConcepts;
  myContents: MyContents;
  myContentsWithEmbeddingOpenaiTextEmbedding3Small1536: MyContentsWithEmbeddingOpenaiTextEmbedding3Small1536;
  myDocuments: MyDocuments;
  mySpaces: MySpaces;
  PlatformAccount: PlatformAccount;
  result: Result;
  Space: Space;
  SpaceAccess: SpaceAccess;
  syncInfo: SyncInfo;
}
