/**
 * This file was generated by kysely-codegen and ts-to-zod
 * Manual edits will be overwritten.
 */

import { z } from "zod";
import { Insertable } from "kysely";
import {Agentidentifiertype, Agenttype, Contentvariant, Embeddingname, Entitytype, Epistemicstatus, Platform, Scale, TaskStatus, Json, JsonValue, JsonArray, JsonObject, Concept, Content, Document, MyAccounts, MyConcepts, MyContents, MyContentsWithEmbeddingOpenaiTextEmbedding3Small1536, MyDocuments, PlatformAccount} from "./kyselyTypes";





export const agentidentifiertypeSchema = z.nativeEnum(Agentidentifiertype);

export const agenttypeSchema = z.nativeEnum(Agenttype);

export const contentvariantSchema = z.nativeEnum(Contentvariant);

export const embeddingnameSchema = z.nativeEnum(Embeddingname);

export const entitytypeSchema = z.nativeEnum(Entitytype);

export const epistemicstatusSchema = z.nativeEnum(Epistemicstatus);

export const platformSchema = z.nativeEnum(Platform);

export const scaleSchema = z.nativeEnum(Scale);

export const taskStatusSchema = z.nativeEnum(TaskStatus);

export const int8Schema = z.union([z.string(), z.bigint(), z.number()]);

export const jsonPrimitiveSchema = z.union([z.boolean(), z.number(), z.string()]).nullable();

export const timestampSchema = z.union([z.date(), z.string()]);

export const accessTokenSchema = z.object({
    accessToken: z.string(),
    code: z.string().nullable(),
    createdDate: timestampSchema.optional(),
    platformAccountId: int8Schema.nullable(),
    requestId: z.string()
});

export const agentIdentifierSchema = z.object({
    accountId: int8Schema,
    identifierType: agentidentifiertypeSchema,
    trusted: z.boolean().optional(),
    value: z.string()
});

export const conceptContributorsSchema = z.object({
    conceptId: int8Schema,
    contributorId: int8Schema
});

export const contentContributorsSchema = z.object({
    contentId: int8Schema,
    contributorId: int8Schema
});

export const contentEmbeddingOpenaiTextEmbedding3Small1536Schema = z.object({
    model: embeddingnameSchema.optional(),
    obsolete: z.boolean().optional().nullable(),
    targetId: int8Schema,
    vector: z.string()
});

export const mySpacesSchema = z.object({
    id: int8Schema.nullable(),
    name: z.string().nullable(),
    platform: platformSchema.nullable(),
    url: z.string().nullable()
});

export const resultSchema = z.object({
    max: timestampSchema.nullable()
});

export const spaceSchema = z.object({
    id: int8Schema.optional(),
    name: z.string(),
    platform: platformSchema,
    url: z.string()
});

export const spaceAccessSchema = z.object({
    accountId: int8Schema,
    editor: z.boolean(),
    spaceId: int8Schema
});

export const syncInfoSchema = z.object({
    failureCount: z.number().optional().nullable(),
    id: z.number().optional(),
    lastTaskEnd: timestampSchema.nullable(),
    lastTaskStart: timestampSchema.nullable(),
    status: taskStatusSchema.optional().nullable(),
    syncFunction: z.string().nullable(),
    syncTarget: int8Schema.nullable(),
    targetType: entitytypeSchema.optional(),
    taskTimesOutAt: timestampSchema.nullable(),
    worker: z.string()
});

export const jsonSchema: z.ZodSchema<Json> = z.lazy(() => jsonValueSchema);

export const jsonValueSchema: z.ZodSchema<JsonValue> = z.lazy(() => z.union([jsonArraySchema, jsonObjectSchema, jsonPrimitiveSchema]));

export const jsonArraySchema: z.ZodSchema<JsonArray> = z.lazy(() => z.array(jsonValueSchema));

export const jsonObjectSchema: z.ZodSchema<JsonObject> = z.lazy(() => z.record(z.string(), z.union([jsonValueSchema, z.undefined()])));

export const conceptSchema: z.ZodSchema<Insertable<Concept>> = z.lazy(() => z.object({
    arity: z.number().optional().nullable(),
    authorId: int8Schema.nullable(),
    created: timestampSchema,
    description: z.string().nullable(),
    epistemicStatus: epistemicstatusSchema.optional(),
    id: int8Schema.optional(),
    isSchema: z.boolean().optional(),
    lastModified: timestampSchema,
    literalContent: jsonSchema.optional(),
    name: z.string(),
    referenceContent: jsonSchema.optional(),
    refs: z.array(int8Schema).optional(),
    representedById: int8Schema.nullable(),
    schemaId: int8Schema.nullable(),
    spaceId: int8Schema
}));

export const contentSchema: z.ZodSchema<Insertable<Content>> = z.lazy(() => z.object({
    authorId: int8Schema.nullable(),
    created: timestampSchema,
    creatorId: int8Schema.nullable(),
    documentId: int8Schema,
    id: int8Schema.optional(),
    lastModified: timestampSchema,
    metadata: jsonSchema.optional(),
    partOfId: int8Schema.nullable(),
    scale: scaleSchema,
    sourceLocalId: z.string().nullable(),
    spaceId: int8Schema.nullable(),
    text: z.string(),
    variant: contentvariantSchema.optional()
}));

export const documentSchema: z.ZodSchema<Insertable<Document>> = z.lazy(() => z.object({
    authorId: int8Schema,
    contents: z.number().nullable(),
    created: timestampSchema,
    id: int8Schema.optional(),
    lastModified: timestampSchema,
    metadata: jsonSchema.optional(),
    sourceLocalId: z.string().nullable(),
    spaceId: int8Schema.nullable(),
    url: z.string().nullable()
}));

export const myAccountsSchema: z.ZodSchema<Insertable<MyAccounts>> = z.lazy(() => z.object({
    accountLocalId: z.string().nullable(),
    active: z.boolean().nullable(),
    agentType: agenttypeSchema.nullable(),
    dgAccount: z.string().nullable(),
    id: int8Schema.nullable(),
    metadata: jsonSchema.nullable(),
    name: z.string().nullable(),
    platform: platformSchema.nullable(),
    writePermission: z.boolean().nullable()
}));

export const myConceptsSchema: z.ZodSchema<Insertable<MyConcepts>> = z.lazy(() => z.object({
    arity: z.number().nullable(),
    authorId: int8Schema.nullable(),
    created: timestampSchema.nullable(),
    description: z.string().nullable(),
    epistemicStatus: epistemicstatusSchema.nullable(),
    id: int8Schema.nullable(),
    isSchema: z.boolean().nullable(),
    lastModified: timestampSchema.nullable(),
    literalContent: jsonSchema.nullable(),
    name: z.string().nullable(),
    referenceContent: jsonSchema.nullable(),
    refs: z.array(int8Schema).nullable(),
    representedById: int8Schema.nullable(),
    schemaId: int8Schema.nullable(),
    spaceId: int8Schema.nullable()
}));

export const myContentsSchema: z.ZodSchema<Insertable<MyContents>> = z.lazy(() => z.object({
    authorId: int8Schema.nullable(),
    created: timestampSchema.nullable(),
    creatorId: int8Schema.nullable(),
    documentId: int8Schema.nullable(),
    id: int8Schema.nullable(),
    lastModified: timestampSchema.nullable(),
    metadata: jsonSchema.nullable(),
    partOfId: int8Schema.nullable(),
    scale: scaleSchema.nullable(),
    sourceLocalId: z.string().nullable(),
    spaceId: int8Schema.nullable(),
    text: z.string().nullable(),
    variant: contentvariantSchema.nullable()
}));

export const myContentsWithEmbeddingOpenaiTextEmbedding3Small1536Schema: z.ZodSchema<Insertable<MyContentsWithEmbeddingOpenaiTextEmbedding3Small1536>> = z.lazy(() => z.object({
    authorId: int8Schema.nullable(),
    created: timestampSchema.nullable(),
    creatorId: int8Schema.nullable(),
    documentId: int8Schema.nullable(),
    id: int8Schema.nullable(),
    lastModified: timestampSchema.nullable(),
    metadata: jsonSchema.nullable(),
    model: embeddingnameSchema.nullable(),
    partOfId: int8Schema.nullable(),
    scale: scaleSchema.nullable(),
    sourceLocalId: z.string().nullable(),
    spaceId: int8Schema.nullable(),
    text: z.string().nullable(),
    variant: contentvariantSchema.nullable(),
    vector: z.string().nullable()
}));

export const myDocumentsSchema: z.ZodSchema<Insertable<MyDocuments>> = z.lazy(() => z.object({
    authorId: int8Schema.nullable(),
    contents: z.number().nullable(),
    created: timestampSchema.nullable(),
    id: int8Schema.nullable(),
    lastModified: timestampSchema.nullable(),
    metadata: jsonSchema.nullable(),
    sourceLocalId: z.string().nullable(),
    spaceId: int8Schema.nullable(),
    url: z.string().nullable()
}));

export const platformAccountSchema: z.ZodSchema<Insertable<PlatformAccount>> = z.lazy(() => z.object({
    accountLocalId: z.string(),
    active: z.boolean().optional(),
    agentType: agenttypeSchema.optional(),
    dgAccount: z.string().nullable(),
    id: int8Schema.optional(),
    metadata: jsonSchema.optional(),
    name: z.string(),
    platform: platformSchema,
    writePermission: z.boolean().optional()
}));
