// Replaces the `mime-types` package, which requires Node's `path` module and so
// cannot load on Obsidian mobile. Values are copied from mime-db so the type
// stored against an uploaded asset does not change.
// Null-prototyped so an attachment named `x.constructor` or `x.__proto__` misses
// rather than returning an inherited member, which is not a string.
const MIME_TYPES_BY_EXTENSION: Record<string, string> = Object.assign(
  Object.create(null) as Record<string, string>,
  {
    // Text. Embeds include transcluded notes, and the caller skips every `text/`
    // attachment, so an extension missing here would start being uploaded.
    "3dml": "text/vnd.in3d.3dml",
    appcache: "text/cache-manifest",
    asm: "text/x-asm",
    c: "text/x-c",
    cc: "text/x-c",
    coffee: "text/coffeescript",
    conf: "text/plain",
    cpp: "text/x-c",
    css: "text/css",
    csv: "text/csv",
    curl: "text/vnd.curl",
    cxx: "text/x-c",
    dcurl: "text/vnd.curl.dcurl",
    def: "text/plain",
    dic: "text/x-c",
    dsc: "text/prs.lines.tag",
    etx: "text/x-setext",
    f: "text/x-fortran",
    f77: "text/x-fortran",
    f90: "text/x-fortran",
    flx: "text/vnd.fmi.flexstor",
    fly: "text/vnd.fly",
    for: "text/x-fortran",
    ged: "text/vnd.familysearch.gedcom",
    gv: "text/vnd.graphviz",
    h: "text/x-c",
    hbs: "text/x-handlebars-template",
    hh: "text/x-c",
    htc: "text/x-component",
    htm: "text/html",
    html: "text/html",
    ics: "text/calendar",
    ifb: "text/calendar",
    in: "text/plain",
    ini: "text/plain",
    jad: "text/vnd.sun.j2me.app-descriptor",
    jade: "text/jade",
    java: "text/x-java-source",
    js: "text/javascript",
    jsx: "text/jsx",
    less: "text/less",
    list: "text/plain",
    litcoffee: "text/coffeescript",
    log: "text/plain",
    lua: "text/x-lua",
    man: "text/troff",
    manifest: "text/cache-manifest",
    markdown: "text/markdown",
    mcurl: "text/vnd.curl.mcurl",
    md: "text/markdown",
    mdx: "text/mdx",
    me: "text/troff",
    mjs: "text/javascript",
    mkd: "text/x-markdown",
    mml: "text/mathml",
    ms: "text/troff",
    n3: "text/n3",
    nfo: "text/x-nfo",
    opml: "text/x-opml",
    p: "text/x-pascal",
    pas: "text/x-pascal",
    pde: "text/x-processing",
    roff: "text/troff",
    rtx: "text/richtext",
    s: "text/x-asm",
    sass: "text/x-sass",
    scss: "text/x-scss",
    scurl: "text/vnd.curl.scurl",
    sfv: "text/x-sfv",
    sgm: "text/sgml",
    sgml: "text/sgml",
    shex: "text/shex",
    shtml: "text/html",
    slim: "text/slim",
    slm: "text/slim",
    spdx: "text/spdx",
    spot: "text/vnd.in3d.spot",
    styl: "text/stylus",
    stylus: "text/stylus",
    sub: "text/vnd.dvb.subtitle",
    t: "text/troff",
    text: "text/plain",
    tr: "text/troff",
    tsv: "text/tab-separated-values",
    ttl: "text/turtle",
    txt: "text/plain",
    uri: "text/uri-list",
    uris: "text/uri-list",
    urls: "text/uri-list",
    uu: "text/x-uuencode",
    vcard: "text/vcard",
    vcf: "text/x-vcard",
    vcs: "text/x-vcalendar",
    vtt: "text/vtt",
    wgsl: "text/wgsl",
    wml: "text/vnd.wap.wml",
    wmls: "text/vnd.wap.wmlscript",
    yaml: "text/yaml",
    yml: "text/yaml",
    ymp: "text/x-suse-ymp",
    // Attachment types Obsidian accepts.
    png: "image/png",
    webp: "image/webp",
    jpg: "image/jpeg",
    jpeg: "image/jpeg",
    gif: "image/gif",
    bmp: "image/bmp",
    svg: "image/svg+xml",
    avif: "image/avif",
    ico: "image/vnd.microsoft.icon",
    tif: "image/tiff",
    tiff: "image/tiff",
    mp3: "audio/mpeg",
    webm: "video/webm",
    wav: "audio/wav",
    m4a: "audio/mp4",
    ogg: "audio/ogg",
    oga: "audio/ogg",
    "3gp": "video/3gpp",
    flac: "audio/x-flac",
    aac: "audio/aac",
    mp4: "video/mp4",
    ogv: "video/ogg",
    mov: "video/quicktime",
    mkv: "video/x-matroska",
    pdf: "application/pdf",
    json: "application/json",
    xml: "application/xml",
  },
);

export const DEFAULT_MIME_TYPE = "application/octet-stream";

export const getMimeTypeForPath = (filePath: string): string => {
  const fileName = filePath.split("/").pop() ?? "";
  const lastDotIndex = fileName.lastIndexOf(".");
  // A leading dot is a dotfile, not an extension.
  if (lastDotIndex <= 0) return DEFAULT_MIME_TYPE;
  const extension = fileName.slice(lastDotIndex + 1).toLowerCase();
  return MIME_TYPES_BY_EXTENSION[extension] ?? DEFAULT_MIME_TYPE;
};
