name: Supabase deploy Function
on:
  workflow_dispatch:
  push:
    branches:
      - feature/supabase
    paths:
      - "projects/database"
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: plzkmulvmuhdpcmnyrhm
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: |
          supabase functions deploy --project-ref ${{ secrets.SUPABASE_PROJECT_ID_PROD }}
          supabase push --project-ref ${{ secrets.SUPABASE_PROJECT_ID_PROD }}
