name: Supabase deploy Function
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    if: false
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: plzkmulvmuhdpcmnyrhm
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: |
          cd projects/database
          supabase functions deploy --project-ref ${{ secrets.PRODUCTION_PROJECT_ID }}
          supabase push --project-ref ${{ secrets.PRODUCTION_PROJECT_ID }}
