name: Database tests
on:
  pull_request:
    paths:
      - "packages/database/**"
env:
  SUPABASE_USE_DB: local
  SUPABASE_PROJECT_ID: test
  GITHUB_TEST: test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.15.1
          run_install: false
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Get supabase version
        working-directory: ./packages/database
        run: echo "SUPABASE_VERSION=$(./node_modules/.bin/supabase --version)" >> $GITHUB_ENV
      - name: Cache Docker images.
        uses: ScribeMD/docker-cache@0.5.0
        with:
          key: docker-${{ runner.os }}-${{ env.SUPABASE_VERSION }}
      - name: Setup database
        working-directory: ./packages/database
        run: pnpm run setup
      - name: Serve and run tests
        working-directory: ./packages/database
        run: pnpm run test:withserve
